apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - image: devopsprozy/python:app-1012
        name: python
        resources: {}
status: {}
